       ORG $0000
       LDAA #!123 ;MODO INMEDIATO CARGA A EN DECIMAL
       LDAB $76   ;LEER DIRECCION $0076 EN B MODO DIRECTO
       INCA       ;MODO INHERENTE
       LDAB $0176 ;CARGA B EN MODO EXTENDIDO